package com.workingbit.share.domain.impl;

import com.amazonaws.services.dynamodbv2.datamodeling.*
import com.workingbit.board.common.DbConstants
import com.workingbit.coremodule.common.EnumArticleStatuses

/**
 * Created by Aleksey Popryaduhin on 18:31 09/08/2017.
 */
@DynamoDBTable(tableName = DbConstants.ARTICLE_TABLE)
public class Article(map: HashMap<String, Any?>) {

    private val id: String by map
        @DynamoDBAutoGeneratedKey @DynamoDBHashKey(attributeName = DbConstants.ID) get

    var authorId: String by map
        @DynamoDBAttribute(attributeName = "authorId") get

    var title: String by map
        @DynamoDBAttribute(attributeName = "title") get

    var content: String by map
        @DynamoDBAttribute(attributeName = "content") get

    var boardId: String by map
        @DynamoDBAttribute(attributeName = "boardId") get

    var status: EnumArticleStatuses by map
        @DynamoDBAttribute(attributeName = "status") @DynamoDBTypeConvertedEnum get
}
