package com.workingbit.coremodule.domain.impl

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey
import com.workingbit.board.common.DbConstants

/**
 * Created by Aleksey Popryaduhin on 16:50 23/08/2017.
 */
class Author(map: HashMap<String, Any?>) {

    private val id: String by map
        @DynamoDBAutoGeneratedKey @DynamoDBHashKey(attributeName = DbConstants.ID) get

    private val vkId: String by map
        @DynamoDBAttribute(attributeName = "vkId") get

    private val fbId: String by map
        @DynamoDBAttribute(attributeName = "fbId") get
}