package com.workingbit.coremodule.domain.impl

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConvertedJson
import com.workingbit.board.common.DbConstants

/**
 * Created by Aleksey Popryaduhin on 18:34 23/08/2017.
 */
class BoardHistory(private val map: HashMap<String, Any?>) {

    private val id: String by map
        @DynamoDBAutoGeneratedKey @DynamoDBHashKey(attributeName = DbConstants.ID) get

    private val boardId: String by map
        @DynamoDBAttribute(attributeName = "boardId") get

    var root: TreeNode<BoardContainer>? by map
        @DynamoDBTypeConvertedJson(targetType = TreeNode::class) @DynamoDBAttribute(attributeName = "root") get

    var current: TreeNode<BoardContainer>? by map
        @DynamoDBTypeConvertedJson(targetType = TreeNode::class) @DynamoDBAttribute(attributeName = "current") get
}