server:
  port: 8002

AWS_ENDPOINT: http://localhost:8083
AWS_DEFAULT_REGION: eu-central-1

CLIENT_URL: http://localhost:4200
ARTICLE_SERVICE_URL: http://localhost:8001

TEST: true

CONTEXT_PATH: /v1
