pipelines:
  default:
    - step:
        caches:
          - gradle
          - node
        script:
          - ./gradlew clean build copyRuntimeLibs batchZip --parallel -x test
          - npm i
          - cd articleservice
          - ../node_modules/./bin/sls deploy
          - cd ../boardservice
          - ../node_modules/./bin/sls deploy
