pipelines:
  default:
    - step:
        caches:
          - gradle
        script:
          - ./gradlew clean build copyRuntimeLibs batchZip --parallel -x test
          - cd wikiservice
          - ./sls deploy
          - cd ../boardservice
          - ./sls deploy
