pipelines:
  default:
    - step:
        caches:
          - gradle
        script:
          - ./gradlew clean build
          - cd wikiservice
          - ./sls deploy
          - cd ../boardservice
          - ./sls deploy
