BOARD_API_URL: https://kv5auqqq20.execute-api.eu-central-1.amazonaws.com/dev
BOARD_RESOURCE: ${BOARD_API_URL}/board

CLIENT_URL: https://wiki.shashki.online

AWS_ENDPOINT: dump
AWS_DEFAULT_REGION: eu-central-1

TEST: false