server:
  port: 8001

BOARD_API_URL: http://localhost:8002/v1
BOARD_RESOURCE: ${BOARD_API_URL}/board

AWS_ENDPOINT: http://localhost:8081
AWS_DEFAULT_REGION: eu-central-1

CLIENT_URL: http://localhost:4200

TEST: true

CONTEXT_PATH: /v1
