package com.workingbit.share.domain.impl;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.workingbit.board.common.DBConstants;
import com.workingbit.share.common.EnumRules;
import com.workingbit.share.domain.IBoard;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

/**
 * Created by Aleksey Popryaduhin on 18:31 09/08/2017.
 */
@DynamoDBTable(tableName = DBConstants.BOARD_TABLE)
@Data
@EqualsAndHashCode(of = {"id"})
@NoArgsConstructor
public class Board implements IBoard {

  @DynamoDBAutoGeneratedKey
  @DynamoDBHashKey(attributeName = "Id")
  private String id;

  @DynamoDBTypeConvertedJson(targetType = BoardChanger.class)
  @DynamoDBAttribute(attributeName = "CurrentBoard")
  private String currentBoardId;

  /**
   * Is player on the black side?
   */
  @DynamoDBAttribute(attributeName = "Black")
  private boolean black;

  @DynamoDBTypeConvertedEnum
  @DynamoDBAttribute(attributeName = "Rules")
  private EnumRules rules;

  /**
   * Size of one square
   */
  @DynamoDBAttribute(attributeName = "SquareSize")
  private int squareSize;

  public Board(String boardId, boolean black, EnumRules rules, int squareSize) {
    this.currentBoardId = boardId;
    this.black = black;
    this.rules = rules;
    this.squareSize = squareSize;
  }
}
