package com.workingbit.share.domain.impl;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.workingbit.board.common.DBConstants;
import com.workingbit.share.domain.IBoardHistory;
import lombok.Data;

/**
 * Created by Aleksey Popryaduhin on 10:02 13/08/2017.
 */
@Data
@DynamoDBTable(tableName = DBConstants.BOARD_HISTORY_TABLE)
public class BoardHistory implements IBoardHistory {

  @DynamoDBAutoGeneratedKey
  @DynamoDBHashKey(attributeName = "Id")
  private String id;

  @DynamoDBTypeConvertedJson(targetType = BoardHistoryNode.class)
  @DynamoDBAttribute(attributeName = "CurrentBoard")
  private BoardHistoryNode currentBoard;

  @DynamoDBTypeConvertedJson(targetType = BoardHistoryNode.class)
  @DynamoDBAttribute(attributeName = "ParentBoard")
  private BoardHistoryNode parentBoard = new BoardHistoryNode();
}
