package com.workingbit.history.domain.impl;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.workingbit.board.common.DBConstants;
import com.workingbit.history.domain.IBoardTree;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Created by Aleksey Popryaduhin on 20:51 13/08/2017.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = DBConstants.BOARD_HISTORY_TABLE)
public class BoardHistory implements IBoardTree {

  @DynamoDBAutoGeneratedKey
  @DynamoDBHashKey(attributeName = "id")
  private String id;

  @DynamoDBAttribute(attributeName = "boardId")
  private String boardId;

  @DynamoDBAttribute(attributeName = "history")
  private String history;
}
