package com.workingbit.history.domain.impl;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.workingbit.board.common.DBConstants;
import com.workingbit.history.domain.IBoardHistory;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Created by Aleksey Popryaduhin on 20:51 13/08/2017.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = DBConstants.BOARD_HISTORY_TABLE)
public class BoardHistory implements IBoardHistory {

  @DynamoDBAutoGeneratedKey
  @DynamoDBHashKey(attributeName = "id")
  private String id;

  @DynamoDBAttribute(attributeName = "boardId")
  private String boardId;

  @DynamoDBTypeConvertedJson(targetType = BoardTreeNode.class)
  @DynamoDBAttribute(attributeName = "history")
  private BoardTreeNode root;

  @DynamoDBTypeConvertedJson(targetType = BoardTreeNode.class)
  @DynamoDBAttribute(attributeName = "history")
  private BoardTreeNode current;
}
